server {
    listen 8080;                  
    host 127.0.0.1;              
    server_name example.com;      
    
    client_max_body_size 100mb;

    
    error_page 404 ./pages/errors/404.html;
    error_page 500 ./pages/errors/500.html;
    error_page 413 ./pages/errors/413.html;
    

    location / {
     root ./pages/;
     index  index.html;
     allowed_methods GET;
     autoindex off;
    }

    location /upload.html{
        root ./pages/uploads/;
        index upload.html;
        allowed_methods GET;
        autoindex off;
    }

    location /uploads{
        root ./pages/uploads/;
        allowed_methods GET POST;
        autoindex on;
    }

    location /new {
        root ./pages/new/;
        index new.html;
        autoindex off;
    }

    location /old {
        root ./pages;
        return 301 /new;
    }

    location /video {
     root ./pages/;
     index  video.mp4;
     autoindex off;
    }

    location *.php {
        root /var/www/cgi-bin;
        allowed_methods GET POST;
        cgi_pass /usr/bin/php;
    }
    location *.py {
        root /var/www/cgi-bin;
        allowed_methods GET POST;
        cgi_pass /usr/local/bin/python3.7;
    }

}
