server {
    # Basic server configuration
    listen 8080 90;                  # Port
    host 127.0.0.1;              # Host
    server_name example.com;      # Optional server name
    
    # Client body size limit
    client_max_body_size 10M;
    
    # Default error pages
    error_page 404 ./pages/errors/404.html;
    error_page 500 ./pages/errors/500.html;
    
    # Basic route with directory configuration
     location / {
     root ./;
     index  index.html;
     autoindex off;
    }

    location /video {
     root /Users/elmountahi/1337/13Projects/WebServ/movie;
     index  video.mp4;
     autoindex off;
    }

    location /uploads{
        root /Users/elmountahi/1337/13Projects/WebServ/uploads;
        allowed_methods GET POST DELETE;
        autoindex on;
    }

    
    # CGI handling route
    # location *.php {
    #     root /var/www/cgi-bin;
    #     allowed_methods GET POST;
    #     cgi_pass /usr/bin/php-cgi;
    # }
    
    # File upload route
    # location /upload {
    #     root /var/www/uploads;
    #     allowed_methods POST;
    #     upload_enable on;
    #     upload_store /var/www/uploads;
    # }
}

# Default server for same host:port
# server {
#     listen 5000;
#     host 127.0.0.1;
#     # No server_name makes this the default server
    
#     location / {
#         root /var/www/default;
#         index index.html;
#         allowed_methods GET;
#         autoindex off;
#     }
# }